### ISSUE TITLE
Error in read_xml.response(x$response, ..., as_html = as_html) : Forbidden (HTTP 403)

### ISSUE THREAD

**Issue by arunrajes** [IndrajeetPatil/kittyR#8] opened 2020-02-04 01:30 UTC
---
Error received after calling kittyR() 
```r
library(remotes)
#remotes::install_github("IndrajeetPatil/kittyR")
library(kittyR)
kittyR::kittyR()
```
Error in read_xml.response(x$response, ..., as_html = as_html) : 
  Forbidden (HTTP 403).
In addition: Warning message:
In request_GET(session, url) : Forbidden (HTTP 403).

**Comment by IndrajeetPatil** [comment] 2020-02-04 07:20
Duplicate of #6

**Closed as completed by IndrajeetPatil** 2020-02-04 07:20 UTC
